# generated by generate_models.py
# ruff: noqa: E501

from datetime import date, time
from typing import Literal, final

from pydantic import AwareDatetime

from synthetic_edi_gen._base import EDIBaseModel


class Address(EDIBaseModel):
    line: str | None = None
    """
    Line. EDI: N301.
    """
    line2: str | None = None
    """
    Line2. EDI: N302.
    """
    city: str
    """
    City. EDI: N401.
    """
    state_code: str | None = None
    """
    State code. EDI: N402.
    """
    zip_code: str | None = None
    """
    Zip code. EDI: N403.
    """
    country_code: str | None = None
    """
    Country code. EDI: N404.
    """
    location_qualifier: str | None = None
    """
    Location qualifier; only used for 834 transaction. Since: v2.14.8. EDI: N405.
    """
    location_identifier: str | None = None
    """
    Location identifier; only used for 834 transaction. Since: v2.14.8. EDI: N406.
    """
    country_subdivision_code: str | None = None
    """
    Country subdivision code; only used for 834 transaction. Since: v2.14.8. EDI: N407.
    """


class AmbulanceTransportInfo(EDIBaseModel):
    """
    Information related to the ambulance service rendered to a patient. Required on all claims involving ambulance transport services. Segment: CR1.
    """

    patient_weight: float | None = None
    """
    Patient weight. EDI: CR102.
    """
    reason_code: str
    """
    Reason code. EDI: CR104.
    """
    reason: (
        Literal[
            "FAMILY_MEMBER",
            "NEAREST_FACILITY",
            "PHYSICIAN",
            "REHAB",
            "RESIDENTIAL_FACILITY",
            "SPECIALIST",
        ]
        | None
    ) = None
    """
    Ambulance transport reason code as constant (enum). EDI: CR104.
    """
    transport_distance: float
    """
    Transport distance. EDI: CR106.
    """
    round_trip_purpose_description: str | None = None
    """
    Round trip purpose description. EDI: CR109.
    """
    stretcher_purpose_description: str | None = None
    """
    Stretcher purpose description. EDI: CR110.
    """


class Amount(EDIBaseModel):
    """
    Segment: AMT.
    """

    qualifier_code: str
    """
    Code specifying the type of amount (amount qualifier code). EDI: AMT01.
    """
    type: str | None = None
    """
    Type of amount; qualifier code translated to a mnemonic string constant (enum). EDI: AMT01.
    """
    amount: float
    """
    Amount. EDI: AMT02.
    """


class Attachment(EDIBaseModel):
    """
    Segment: PWK.
    """

    report_type_code: str
    """
    Report type code. EDI: PWK01.
    """
    report_transmission_code: str
    """
    Report transmission code. EDI: PWK02.
    """
    control_number: str | None = None
    """
    Control number. EDI: PWK06.
    """


class Code(EDIBaseModel):
    """
    Code and description.
    """

    sub_type: str | None = None
    """
    Healthcare code subtype, such as CPT, HCPCS, ICD_10, NDC.
    """
    code: str
    """
    Healthcare code.
    """
    desc: str | None = None
    """
    Code description.
    """


class Adjustment(EDIBaseModel):
    """
    Segment: CAS.
    """

    group: (
        Literal[
            "CONTRACTUAL",
            "CORRECTION",
            "OTHER",
            "PATIENT_RESPONSIBILITY",
            "PAYOR_INITIATED",
        ]
        | None
    ) = None
    """
    Claim adjustment group code as a string constant (enum). EDI: CAS01.
    """
    reason: Code | None = None
    """
    Claim adjustment reason code. EDI: CAS02.
    """
    amount: float
    """
    Adjustment amount. EDI: CAS03.
    """
    quantity: float | None = None
    """
    Adjustment quantity. EDI: CAS04.
    """


class CodeAndAmount(Code):
    amount: float | None = None
    """
    Amount. EDI: HI01-5.
    """


class CodeAndDate(Code):
    occurrence_date: date
    """
    Occurrence date. EDI: HI01-4.
    """


class ConditionsIndicator(EDIBaseModel):
    """
    Segment: CRC.
    """

    category_code: str
    """
    Category code. EDI: CRC01.
    """
    category: (
        Literal[
            "AMBULANCE_CERTIFICATION",
            "EPSDT_MUTUALLY_DEFINED",
            "VISION_CONTACT_LENSES",
            "VISION_SPECTACLE_FRAMES",
            "VISION_SPECTACLE_LENSES",
        ]
        | None
    ) = None
    """
    Category code as constant (enum). EDI: CRC01.
    """
    yes_or_no_condition: str
    """
    Yes or no condition. EDI: CRC02.
    """
    condition_codes: list[str] | None = None
    """
    Condition codes. EDI: CRC03, CRC04, CRC05, CRC06, CRC07.
    """


class ContactNumber(EDIBaseModel):
    """
    Segment: PER.
    """

    type: Literal[
        "ALTERNATE_PHONE",
        "BEEPER",
        "CELL_PHONE",
        "EMAIL",
        "EXTENSION",
        "FAX",
        "HOME_PHONE",
        "PHONE",
        "UNKNOWN",
        "URL",
        "WORK_PHONE",
    ]
    """
    Type of contact number. EDI: PER03, PER05, PER07.
    """
    number: str
    """
    Number. EDI: PER04, PER06, PER08.
    """


class ContactInfo(EDIBaseModel):
    """
    Segment: PER.
    """

    function_code: str
    """
    Function code. EDI: PER01.
    """
    name: str | None = None
    """
    Name. EDI: PER02.
    """
    contact_numbers: list[ContactNumber] | None = None
    """
    Contact numbers.
    """


class ContractInfo(EDIBaseModel):
    """
    Required when the submitter is contractually obligated to supply this information on post-adjudicated claims. Segment: CN1.
    """

    contract_type_code: str
    """
    Contract type code. EDI: CN101.
    """
    amount: float | None = None
    """
    Amount. EDI: CN102.
    """
    percentage: float | None = None
    """
    Percentage. EDI: CN103.
    """
    contract_code: str | None = None
    """
    Contract code. EDI: CN104.
    """
    term_discount_percentage: float | None = None
    """
    Term discount percentage. EDI: CN105.
    """
    version_identifier: str | None = None
    """
    Version identifier. EDI: CN106.
    """


class DmeCertification(EDIBaseModel):
    """
    DME Certification. Required when a Durable Medical Equipment Regional Carrier Certificate of Medical Necessity (DMERC CMN) or a DMERC Information Form (DIF) or Oxygen Therapy Certification is included on this service line. Segment: CR3.
    """

    certification_type_code: str
    """
    Certification type code. EDI: CR301.
    """
    duration: float
    """
    Length of time DME equipment is needed, in months. EDI: CR303.
    """


class FileInfo(EDIBaseModel):
    name: str | None = None
    """
    File name.
    """
    url: str | None = None
    """
    URL of the file, including the full path.
    """
    last_modified_date_time: AwareDatetime | None = None
    """
    Last modified date and time of the file.
    """


class InpatientAdjudication(EDIBaseModel):
    """
    Contains Remittance Advice Remark Codes at the claim level and/or Medicare or Medicaid-specific amounts for inpatient institutional claims. Segment: MIA.
    """

    covered_days_or_visits_count: int
    """
    Covered days or visits count. EDI: MIA01.
    """
    pps_operating_outlier_amount: float | None = None
    """
    Pps operating outlier amount. EDI: MIA02.
    """
    lifetime_psychiatric_days_count: int | None = None
    """
    Lifetime psychiatric days count. EDI: MIA03.
    """
    drg_amount: float | None = None
    """
    Drg amount. EDI: MIA04.
    """
    disproportionate_share_amount: float | None = None
    """
    Disproportionate share amount. EDI: MIA06.
    """
    msp_pass_through_amount: float | None = None
    """
    Msp pass through amount. EDI: MIA07.
    """
    pps_capital_amount: float | None = None
    """
    Pps capital amount. EDI: MIA08.
    """
    pps_capital_fsp_drg_amount: float | None = None
    """
    Pps capital fsp drg amount. EDI: MIA09.
    """
    pps_capital_hsp_drg_amount: float | None = None
    """
    Pps capital hsp drg amount. EDI: MIA10.
    """
    pps_capital_dsh_drg_amount: float | None = None
    """
    Pps capital dsh drg amount. EDI: MIA11.
    """
    old_capital_amount: float | None = None
    """
    Old capital amount. EDI: MIA12.
    """
    pps_capital_ime_amount: float | None = None
    """
    Pps capital ime amount. EDI: MIA13.
    """
    pps_operating_hospital_specific_drg_amount: float | None = None
    """
    Pps operating hospital specific drg amount. EDI: MIA14.
    """
    cost_report_day_count: int | None = None
    """
    Cost report day count. EDI: MIA15.
    """
    pps_operating_federal_specific_drg_amount: float | None = None
    """
    Pps operating federal specific drg amount. EDI: MIA16.
    """
    pps_capital_outlier_amount: float | None = None
    """
    Pps capital outlier amount. EDI: MIA17.
    """
    indirect_teaching_amount: float | None = None
    """
    Indirect teaching amount. EDI: MIA18.
    """
    non_payable_professional_component_amount: float | None = None
    """
    Non payable professional component amount. EDI: MIA19.
    """
    pps_capital_exception_amount: float | None = None
    """
    Pps capital exception amount. EDI: MIA24.
    """
    remarks: list[Code] | None = None
    """
    Remark codes. EDI: MIA05, MIA20, MIA21, MIA22, MIA23.
    """


class InstDiagnosis(Code):
    present_on_admission_indicator: str | None = None
    """
    Present on admission indicator. EDI: HI01-9.
    """


class OrthodonticInfo(EDIBaseModel):
    """
    Segment: DN1.
    """

    treatment_months_count: float | None = None
    """
    Treatment months count. EDI: DN101.
    """
    treatment_months_remaining_count: float | None = None
    """
    Treatment months remaining count. EDI: DN102.
    """
    treatment_indicator: str | None = None
    """
    Treatment indicator. EDI: DN104.
    """


class OutpatientAdjudication(EDIBaseModel):
    """
    Contains Remittance Advice Remark Codes at the claim level and/or Medicare or Medicaid-specific amounts for outpatient claims. Segment: MOA.
    """

    reimbursement_rate: float | None = None
    """
    Reimbursement rate. EDI: MOA01.
    """
    hcpcs_payable_amount: float | None = None
    """
    Claim HCPCS Payable Amount. EDI: MOA02.
    """
    esrd_payment_amount: float | None = None
    """
    Esrd payment amount. EDI: MOA08.
    """
    non_payable_professional_component_amount: float | None = None
    """
    Nonpayable Professional Component Amount. EDI: MOA09.
    """
    remarks: list[Code] | None = None
    """
    Remark codes.
    """


class PartyIdName(EDIBaseModel):
    entity_role: str
    """
    Entity role. EDI: NM101, N101.
    """
    entity_type: str | None = None
    """
    Entity type. EDI: NM102.
    """
    identification_type: str | None = None
    """
    Identification type, e.g., NPI or EIN. This is a qualifier code translated to a string constant (enum). EDI: NM108, N103.
    """
    identifier: str | None = None
    """
    Identifier. EDI: NM109, N104.
    """
    tax_id: str | None = None
    """
    Tax id. EDI: REF02 *TJ, REF02 *SY, REF02 *EI.
    """
    last_name_or_org_name: str | None = None
    """
    Organization name or person last name. EDI: NM103, N102.
    """
    first_name: str | None = None
    """
    First name. EDI: NM104.
    """
    middle_name: str | None = None
    """
    Middle name. EDI: NM105.
    """


class Procedure(Code):
    modifiers: list[Code] | None = None
    """
    Modifiers.
    """


class Adjudication(EDIBaseModel):
    """
    Loop: 2430; Segment: SVD.
    """

    payer_identifier: str | None = None
    """
    Payer identifier. EDI: SVD01.
    """
    paid_amount: float | None = None
    """
    Paid amount. EDI: SVD02.
    """
    unit_count: float | None = None
    """
    Unit count. EDI: SVD05.
    """
    bundled_or_unbundled_line_number: int | None = None
    """
    Bundled or unbundled line number. EDI: SVD06.
    """
    procedure: Procedure | None = None
    """
    Procedure. EDI: SVD03.
    """
    adjustments: list[Adjustment] | None = None
    """
    Line adjustments. EDI: CAS.
    """
    adjudication_or_payment_date: date | None = None
    """
    Adjudication or payment date. EDI: DTP03 *573.
    """
    remaining_patient_liability_amount: float | None = None
    """
    Remaining patient liability amount. EDI: AMT02 *EAF.
    """


class ProviderAdjustmentReasonAmount(EDIBaseModel):
    """
    Provider-level payment adjustment containing the reason code and the amount.
    """

    reason: Code
    """
    Provider adjustment reason code. EDI: PLB03-1.
    """
    reference_identification: str | None = None
    """
    Reference identification. EDI: PLB03-2.
    """
    amount: float
    """
    Amount. EDI: PLB04.
    """


class Quantity(EDIBaseModel):
    """
    Segment: QTY.
    """

    qualifier_code: str
    """
    Code specifying the type of quantity (quantity qualifier code). EDI: QTY01.
    """
    type: str | None = None
    """
    Type of quantity; qualifier code translated to a mnemonic string constant (enum). EDI: QTY01.
    """
    quantity: float
    """
    Quantity. EDI: QTY02.
    """


class Reference(EDIBaseModel):
    """
    Segment: REF.
    """

    qualifier_code: str
    """
    Code qualifying the reference identification. EDI: REF01.
    """
    type: str | None = None
    """
    Type of reference; qualifier code as a string constant (enum). EDI: REF01.
    """
    identification: str
    """
    Reference identification. EDI: REF02.
    """


class Party(PartyIdName):
    address: Address | None = None
    """
    Address.
    """
    contacts: list[ContactInfo] | None = None
    """
    Contacts.
    """
    additional_ids: list[Reference] | None = None
    """
    Other identifications. EDI: REF.
    """


class PatientSubscriber835(EDIBaseModel):
    """
    Insured subscriber of patient for 835.
    """

    person: Party | None = None
    """
    Person. EDI: NM1.
    """


class PersonWithDemographic(Party):
    birth_date: date | None = None
    """
    Birth date. EDI: DMG02.
    """
    gender: Literal["FEMALE", "MALE", "UNKNOWN"] | None = None
    """
    Gender. EDI: DMG03.
    """


class OtherSubscriber(EDIBaseModel):
    payer_responsibility_sequence: Literal[
        "EIGHT",
        "ELEVEN",
        "FIVE",
        "FOUR",
        "NINE",
        "PRIMARY",
        "SECONDARY",
        "SEVEN",
        "SIX",
        "TEN",
        "TERTIARY",
        "UNKNOWN",
    ]
    """
    Payer responsibility sequence. EDI: SBR01.
    """
    relationship_type: (
        Literal[
            "CADAVER_DONOR",
            "CHILD",
            "EMPLOYEE",
            "LIFE_PARTNER",
            "ORGAN_DONOR",
            "OTHER",
            "SELF",
            "SPOUSE",
            "UNKNOWN",
        ]
        | None
    ) = None
    """
    Relationship type. EDI: SBR02, PAT01.
    """
    group_or_policy_number: str | None = None
    """
    Group or policy number. EDI: SBR03.
    """
    group_name: str | None = None
    """
    Group name. EDI: SBR04.
    """
    claim_filing_indicator_code: str | None = None
    """
    Claim filing indicator code. EDI: SBR09.
    """
    insurance_plan_type: (
        Literal[
            "AUTOMOBILE_MEDICAL",
            "BCBS",
            "CHAMPUS",
            "COMMERCIAL",
            "EPO",
            "FEDERAL_EMPLOYEE_PROGRAM",
            "HMO",
            "HMO_MEDICARE",
            "INDEMNITY_INSURANCE",
            "MEDICAID",
            "MEDICARE_A",
            "MEDICARE_B",
            "MUTUALLY_DEFINED",
            "OTHER_FEDERAL",
            "OTHER_NON_FEDERAL",
            "POS",
            "PPO",
            "VETERAN_AFFAIRS",
            "WORKERS_COMPENSATION",
        ]
        | None
    ) = None
    """
    Insurance plan type. EDI: SBR09.
    """
    person: PersonWithDemographic | None = None
    """
    Person. EDI: NM1.
    """
    adjustments: list[Adjustment] | None = None
    """
    Claim-level adjustments from this payer. EDI: CAS.
    """
    payer_paid_amount: float | None = None
    """
    Payer paid amount. EDI: AMT02 *D.
    """
    non_covered_amount: float | None = None
    """
    Non covered amount. EDI: AMT02 *A8.
    """
    remaining_patient_liability_amount: float | None = None
    """
    Remaining patient liability amount. EDI: AMT02 *EAF.
    """
    outpatient_adjudication: OutpatientAdjudication | None = None
    """
    Outpatient adjudication. EDI: MOA.
    """
    payer_prior_authorization_number: str | None = None
    """
    Payer prior authorization number. EDI: REF02 *G1.
    """
    payer_referral_number: str | None = None
    """
    Payer referral number. EDI: REF02 *9F.
    """
    payer_claim_control_number: str | None = None
    """
    Payer claim control number. EDI: REF02 *F8.
    """
    payer: Party | None = None
    """
    Payer. EDI: NM1 *PR; Loop: 2330B.
    """
    providers: list[Party] | None = None
    """
    Other payer's providers. EDI: NM1.
    """


class Patient(EDIBaseModel):
    relationship_type: (
        Literal[
            "CADAVER_DONOR",
            "CHILD",
            "EMPLOYEE",
            "LIFE_PARTNER",
            "ORGAN_DONOR",
            "OTHER",
            "SELF",
            "SPOUSE",
            "UNKNOWN",
        ]
        | None
    ) = None
    """
    Relationship type. EDI: SBR02, PAT01.
    """
    person: PersonWithDemographic | None = None
    """
    Person. EDI: NM1.
    """
    death_date: date | None = None
    """
    Death date. EDI: PAT06.
    """
    weight: float | None = None
    """
    Patient weight in pounds. EDI: PAT08.
    """
    pregnancy_indicator: str | None = None
    """
    Pregnancy indicator. EDI: PAT09.
    """


class Provider(Party):
    provider_taxonomy: Code | None = None
    """
    Provider's specialty information (taxonomy). Populated only for billing, rendering, operating providers. EDI: PRV.
    """


class InstLine(EDIBaseModel):
    """
    Loop: 2400; Segment: SV2.
    """

    source_line_id: str | None = None
    """
    Line item control number. EDI: REF02 *6R.
    """
    repriced_reference_number: str | None = None
    """
    Repriced reference number. EDI: REF02 *9B.
    """
    adjusted_repriced_reference_number: str | None = None
    """
    Adjusted repriced reference number. EDI: REF02 *9D.
    """
    charge_amount: float
    """
    Charge amount. EDI: SV203.
    """
    non_covered_amount: float | None = None
    """
    Non covered amount. EDI: SV207.
    """
    service_tax_amount: float | None = None
    """
    Service tax amount. EDI: AMT02 *GT.
    """
    facility_tax_amount: float | None = None
    """
    Facility tax amount. EDI: AMT02 *N8.
    """
    service_date_from: date | None = None
    """
    Service date from. EDI: DTP03 *472.
    """
    service_date_to: date | None = None
    """
    Service date to. EDI: DTP03 *472.
    """
    unit_type: str
    """
    Unit type. EDI: SV204.
    """
    unit_count: float
    """
    Unit count. EDI: SV205.
    """
    third_party_note: str | None = None
    """
    Third party note. EDI: NTE02 *TPO.
    """
    procedure: Procedure | None = None
    """
    Procedure. EDI: SV202 *HC, SV202 *AD, SV202 *WK, SV202 *IV.
    """
    revenue_code: Code | None = None
    """
    Revenue code. EDI: SV201 *RC,NU.
    """
    attachments: list[Attachment] | None = None
    """
    Attachments. EDI: PWK.
    """
    contract_info: ContractInfo | None = None
    """
    Contract info. EDI: CN1.
    """
    providers: list[Provider] | None = None
    """
    Providers for this service line.
    """
    adjudications: list[Adjudication] | None = None
    """
    Adjudications. EDI: SVD; Loop: 2430.
    """
    adjustments: list[Adjustment] | None = None
    """
    Copy of line adjustments from the adjudication list for backward compatibility. EDI: CAS.
    """
    fixed_format_records: list[str] | None = None
    """
    Fixed format records. EDI: K301.
    """


class PaymentLine(EDIBaseModel):
    """
    Loop: 2110; Segment: SVC.
    """

    source_line_id: str | None = None
    """
    Line item control number. EDI: REF02 *6R.
    """
    repriced_reference_number: str | None = None
    """
    Repriced reference number. EDI: REF02 *9B.
    """
    adjusted_repriced_reference_number: str | None = None
    """
    Adjusted repriced reference number. EDI: REF02 *9D.
    """
    healthcare_policy_id: str | None = None
    """
    Healthcare policy id. EDI: REF02 *0K.
    """
    charge_amount: float
    """
    Charge amount. EDI: SVC02.
    """
    paid_amount: float
    """
    Paid amount. EDI: SVC03.
    """
    supplemental_amounts: list[Amount] | None = None
    """
    Supplemental amounts, such as allowed amount, deduction amount, etc. EDI: AMT.
    """
    supplemental_quantities: list[Quantity] | None = None
    """
    Supplemental quantities. EDI: QTY.
    """
    service_date_from: date | None = None
    """
    Service date from. EDI: DTP03 *472.
    """
    service_date_to: date | None = None
    """
    Service date to. EDI: DTP03 *472.
    """
    unit_count: float | None = None
    """
    Unit count. EDI: SVC05.
    """
    original_unit_count: float | None = None
    """
    Original unit count. EDI: SVC07.
    """
    drug: Code | None = None
    """
    Drug code (NDC). EDI: SVC01.
    """
    procedure: Procedure | None = None
    """
    Procedure. EDI: SVC01 *HC, SVC01 *AD, SVC01 *WK, SVC01 *IV.
    """
    revenue_code: Code | None = None
    """
    Revenue code. EDI: SVC01 *RC,NU, SVC04 *RC,NU.
    """
    original_procedure: Procedure | None = None
    """
    Submitted procedure code from the claim if it is different from the adjudicated procedure. EDI: SVC06 *HC, SVC06 *AD, SVC06 *WK, SVC06 *IV.
    """
    original_revenue_code: Code | None = None
    """
    Submitted revenue code from the claim if it is different from the adjudicated revenue code. EDI: SVC06 *RC,NU.
    """
    original_drug: Code | None = None
    """
    Submitted drug (NDC) code from the claim if it is different from the adjudicated drug code. EDI: SVC06.
    """
    providers: list[Provider] | None = None
    """
    Providers for this service line.
    """
    adjustments: list[Adjustment] | None = None
    """
    Line adjustments. EDI: CAS.
    """
    remark_codes: list[str] | None = None
    """
    Remark codes. EDI: LQ.
    """
    remarks: list[Code] | None = None
    """
    Remark codes. EDI: LQ.
    """
    service_ids: list[Reference] | None = None
    """
    Related service-specific identifiers that were used in the process of adjudicating this service. EDI: REF.
    """
    rendering_provider_ids: list[Reference] | None = None
    """
    Rendering provider identifiers. EDI: REF.
    """


class ProfLine(EDIBaseModel):
    """
    Loop: 2400; Segment: SV1.
    """

    source_line_id: str | None = None
    """
    Line item control number. EDI: REF02 *6R.
    """
    place_of_service_code: str | None = None
    """
    Place of service code. EDI: SV105.
    """
    emergency_indicator: str | None = None
    """
    Emergency indicator. EDI: SV109.
    """
    epsdt_indicator: str | None = None
    """
    Epsdt indicator. EDI: SV111.
    """
    family_planning_indicator: str | None = None
    """
    Family planning indicator. EDI: SV112.
    """
    copay_status_code: str | None = None
    """
    Copay status code. EDI: SV115.
    """
    repriced_reference_number: str | None = None
    """
    Repriced reference number. EDI: REF02 *9B.
    """
    adjusted_repriced_reference_number: str | None = None
    """
    Adjusted repriced reference number. EDI: REF02 *9D.
    """
    prior_authorization: str | None = None
    """
    Prior authorization. EDI: REF02 *G1.
    """
    referral_number: str | None = None
    """
    Referral number. EDI: REF02 *9F.
    """
    charge_amount: float
    """
    Charge amount. EDI: SV102.
    """
    sales_tax_amount: float | None = None
    """
    Sales tax amount. EDI: AMT02 *T.
    """
    service_date_from: date | None = None
    """
    Service date from. EDI: DTP03 *472.
    """
    service_date_to: date | None = None
    """
    Service date to. EDI: DTP03 *472.
    """
    prescription_date: date | None = None
    """
    Prescription date. EDI: DTP03 *471.
    """
    last_certification_date: date | None = None
    """
    Last certification date. EDI: DTP03 *461.
    """
    certification_revision_date: date | None = None
    """
    Certification revision date. EDI: DTP03 *607.
    """
    begin_therapy_date: date | None = None
    """
    Begin therapy date. EDI: DTP03 *463.
    """
    last_seen_date: date | None = None
    """
    Last seen date. EDI: DTP03 *304.
    """
    test_performed_date: date | None = None
    """
    Test performed date. EDI: DTP03 *738, DTP03 *739.
    """
    last_x_ray_date: date | None = None
    """
    Last xray date. EDI: DTP03 *455.
    """
    initial_treatment_date: date | None = None
    """
    Initial treatment date. EDI: DTP03 *454.
    """
    unit_type: str
    """
    Unit type. EDI: SV103.
    """
    unit_count: float
    """
    Unit count. EDI: SV104.
    """
    ambulance_patient_count: int | None = None
    """
    Ambulance patient count. EDI: QTY02 *PT.
    """
    drug: Code | None = None
    """
    Drug code (NDC). EDI: LIN03.
    """
    drug_quantity: float | None = None
    """
    Drug quantity. EDI: CTP04.
    """
    drug_unit_type: str | None = None
    """
    Drug unit type. EDI: CTP05-1.
    """
    prescription_number: str | None = None
    """
    Prescription number. EDI: REF02 *XZ.
    """
    line_note: str | None = None
    """
    Line note. EDI: NTE02 *ADD, NTE02 *DCP.
    """
    third_party_note: str | None = None
    """
    Third party note. EDI: NTE02 *TPO.
    """
    procedure: Procedure | None = None
    """
    Procedure. EDI: SV101 *HC, SV101 *AD, SV101 *WK, SV101 *IV.
    """
    attachments: list[Attachment] | None = None
    """
    Attachments. EDI: PWK.
    """
    contract_info: ContractInfo | None = None
    """
    Contract info. EDI: CN1.
    """
    ambulance_transport_info: AmbulanceTransportInfo | None = None
    """
    Ambulance transport info. EDI: CR1.
    """
    dme_certification: DmeCertification | None = None
    """
    Dme certification. EDI: CR3.
    """
    conditions_indicators: list[ConditionsIndicator] | None = None
    """
    Conditions indicators. EDI: CRC.
    """
    providers: list[Provider] | None = None
    """
    Providers for this service line.
    """
    adjudications: list[Adjudication] | None = None
    """
    Adjudications. EDI: SVD; Loop: 2430.
    """
    adjustments: list[Adjustment] | None = None
    """
    Copy of line adjustments from the adjudication list for backward compatibility. EDI: CAS.
    """
    fixed_format_records: list[str] | None = None
    """
    Fixed format records. EDI: K301.
    """
    diag_pointers: list[int]
    """
    Diagnosis pointers. Each pointer is an index of the diagnosis in the 'diags' array at the claim level. EDI: SV107.
    """
    diags: list[Code] | None = None
    """
    Copy of diagnosis codes from the claim based on diagnosis pointers. EDI: SV107.
    """


class RelatedCauseInfo(EDIBaseModel):
    related_cause_code: str | None = None
    """
    Related cause code. EDI: CLM11-1.
    """
    related_cause_code2: str | None = None
    """
    Related cause code2. EDI: CLM11-2.
    """
    state_code: str | None = None
    """
    State code. EDI: CLM11-4.
    """
    country_code: str | None = None
    """
    Country code. EDI: CLM11-5.
    """


class SpinalManipulationInfo(EDIBaseModel):
    """
    Spinal manipulation service info. Required on chiropractic claims involving spinal manipulation when the information is known to impact the payer’s adjudication process. Segment: CR2.
    """

    condition_code: str
    """
    Condition code. EDI: CR208.
    """
    description: str | None = None
    """
    Description of the patient’s condition. EDI: CR210.
    """
    additional_description: str | None = None
    """
    Additional description of the patient’s condition. EDI: CR211.
    """


class Subscriber(EDIBaseModel):
    payer_responsibility_sequence: Literal[
        "EIGHT",
        "ELEVEN",
        "FIVE",
        "FOUR",
        "NINE",
        "PRIMARY",
        "SECONDARY",
        "SEVEN",
        "SIX",
        "TEN",
        "TERTIARY",
        "UNKNOWN",
    ]
    """
    Payer responsibility sequence. EDI: SBR01.
    """
    relationship_type: (
        Literal[
            "CADAVER_DONOR",
            "CHILD",
            "EMPLOYEE",
            "LIFE_PARTNER",
            "ORGAN_DONOR",
            "OTHER",
            "SELF",
            "SPOUSE",
            "UNKNOWN",
        ]
        | None
    ) = None
    """
    Relationship type. EDI: SBR02, PAT01.
    """
    group_or_policy_number: str | None = None
    """
    Group or policy number. EDI: SBR03.
    """
    group_name: str | None = None
    """
    Group name. EDI: SBR04.
    """
    claim_filing_indicator_code: str | None = None
    """
    Claim filing indicator code. EDI: SBR09.
    """
    insurance_plan_type: (
        Literal[
            "AUTOMOBILE_MEDICAL",
            "BCBS",
            "CHAMPUS",
            "COMMERCIAL",
            "EPO",
            "FEDERAL_EMPLOYEE_PROGRAM",
            "HMO",
            "HMO_MEDICARE",
            "INDEMNITY_INSURANCE",
            "MEDICAID",
            "MEDICARE_A",
            "MEDICARE_B",
            "MUTUALLY_DEFINED",
            "OTHER_FEDERAL",
            "OTHER_NON_FEDERAL",
            "POS",
            "PPO",
            "VETERAN_AFFAIRS",
            "WORKERS_COMPENSATION",
        ]
        | None
    ) = None
    """
    Insurance plan type. EDI: SBR09.
    """
    person: PersonWithDemographic | None = None
    """
    Person. EDI: NM1.
    """
    death_date: date | None = None
    """
    Death date. EDI: PAT06.
    """
    weight: float | None = None
    """
    Patient weight in pounds. EDI: PAT08.
    """
    pregnancy_indicator: str | None = None
    """
    Pregnancy indicator. EDI: PAT09.
    """
    property_casualty_claim_number: str | None = None
    """
    Property casualty claim number. EDI: REF02 *Y4.
    """
    payer: Party | None = None
    """
    Payer. EDI: NM1 *PR; Loop: 2330B.
    """


class ToothInfo(EDIBaseModel):
    """
    Segment: TOO.
    """

    code: str | None = None
    """
    Code. EDI: TOO02.
    """
    surface_codes: list[str] | None = None
    """
    Surface codes. EDI: TOO03.
    """


class DentLine(EDIBaseModel):
    """
    Loop: 2400; Segment: SV3.
    """

    source_line_id: str | None = None
    """
    Line item control number. EDI: REF02 *6R.
    """
    oral_cavity_designation_codes: list[str] | None = None
    """
    Oral cavity designation codes. EDI: SV304.
    """
    prosthesis_crown_or_inlay_code: str | None = None
    """
    Prosthesis crown or inlay code. EDI: SV305.
    """
    predetermination_of_benefits_identifier: str | None = None
    """
    Predetermination of benefits identifier. EDI: REF02 *G3.
    """
    repriced_reference_number: str | None = None
    """
    Repriced reference number. EDI: REF02 *9B.
    """
    adjusted_repriced_reference_number: str | None = None
    """
    Adjusted repriced reference number. EDI: REF02 *9D.
    """
    prior_authorization: str | None = None
    """
    Prior authorization. EDI: REF02 *G1.
    """
    referral_number: str | None = None
    """
    Referral number. EDI: REF02 *9F.
    """
    charge_amount: float
    """
    Charge amount. EDI: SV302.
    """
    sales_tax_amount: float | None = None
    """
    Sales tax amount. EDI: AMT02 *T.
    """
    service_date_from: date | None = None
    """
    Service date from. EDI: DTP03 *472.
    """
    service_date_to: date | None = None
    """
    Service date to. EDI: DTP03 *472.
    """
    prior_placement_date: date | None = None
    """
    Prior placement date. EDI: DTP03 *441, DTP03 *139.
    """
    orthodontic_banding_date: date | None = None
    """
    Orthodontic banding date. EDI: DTP03 *452.
    """
    replacement_date: date | None = None
    """
    Replacement date. EDI: DTP03 *446.
    """
    treatment_start_date: date | None = None
    """
    Treatment start date. EDI: DTP03 *196.
    """
    treatment_completion_date: date | None = None
    """
    Treatment completion date. EDI: DTP03 *198.
    """
    unit_count: float | None = None
    """
    Unit count. EDI: SV306.
    """
    procedure: Procedure | None = None
    """
    Procedure. EDI: SV302 *HC, SV302 *AD, SV302 *WK, SV302 *IV.
    """
    attachments: list[Attachment] | None = None
    """
    Attachments. EDI: PWK.
    """
    contract_info: ContractInfo | None = None
    """
    Contract info. EDI: CN1.
    """
    providers: list[Provider] | None = None
    """
    Providers for this service line.
    """
    adjudications: list[Adjudication] | None = None
    """
    Adjudications. EDI: SVD; Loop: 2430.
    """
    adjustments: list[Adjustment] | None = None
    """
    Copy of line adjustments from the adjudication list for backward compatibility. EDI: CAS.
    """
    fixed_format_records: list[str] | None = None
    """
    Fixed format records. EDI: K301.
    """
    tooth_infos: list[ToothInfo] | None = None
    """
    Tooth infos.
    """
    diag_pointers: list[int]
    """
    Diagnosis pointers. Each pointer is an index of the diagnosis in the 'diags' array at the claim level. EDI: SV302.
    """
    diags: list[Code] | None = None
    """
    Copy of diagnosis codes from the claim based on diagnosis pointers. EDI: SV302.
    """


class ToothStatus(EDIBaseModel):
    """
    Segment: DN2.
    """

    tooth_number: str | None = None
    """
    Tooth number. EDI: DN201.
    """
    status_code: str | None = None
    """
    Status code. EDI: DN202.
    """


class Transaction835(EDIBaseModel):
    control_number: str
    """
    Control number. EDI: ST02.
    """
    transaction_type: str | None = None
    """
    Transaction type translated to string constant, PROF for 837P, INST for 837I, etc. EDI: ST01, ST03.
    """
    production_date: date | None = None
    """
    Production date. EDI: DTP03 *405.
    """
    transaction_handling_type: str
    """
    Transaction handling type. EDI: BPR01.
    """
    total_payment_amount: float
    """
    Total payment amount. EDI: BPR02.
    """
    credit_or_debit_flag_code: str
    """
    Credit or debit flag code. EDI: BPR03.
    """
    payment_method_type: str
    """
    Payment method type: ACH, CHECK, WIRE_TRANSFER, NON_PAYMENT. EDI: BPR04.
    """
    payment_format_code: str | None = None
    """
    Payment format code. EDI: BPR05.
    """
    sender_bank_routing_number: str | None = None
    """
    Sender bank routing number. EDI: BPR07.
    """
    sender_account_number: str | None = None
    """
    Sender account number. EDI: BPR09.
    """
    originating_company_id: str | None = None
    """
    If provided, should be identical to payerIdentifier. EDI: BPR10.
    """
    originating_company_supplemental_code: str | None = None
    """
    Originating company supplemental code. EDI: BPR11, TRN04.
    """
    receiver_bank_routing_number: str | None = None
    """
    Receiver bank routing number. EDI: BPR13.
    """
    receiver_account_number: str | None = None
    """
    Receiver account number. EDI: BPR15.
    """
    payment_date: date
    """
    Payment date. EDI: BPR16.
    """
    check_or_eft_trace_number: str
    """
    Check or eft trace number. EDI: TRN02.
    """
    payer_identifier: str
    """
    This must be a 1 followed by the payer's EIN or TIN. This ID will be used as the identifier in the payer object if no other identifier was provided. EDI: TRN03.
    """
    receiver_identifier: str | None = None
    """
    Receiver's identifier when different from payee (e.g., a clearinghouse). EDI: REF02 *EV.
    """
    transaction_set_identifier_code: str | None = None
    """
    Transaction set identifier code. EDI: ST01.
    """
    implementation_convention_reference: str | None = None
    """
    Implementation convention reference. EDI: ST03.
    """
    file_info: FileInfo | None = None
    """
    File info.
    """


@final
class Payment(EDIBaseModel):  # pyright: ignore[reportUninitializedInstanceVariable]
    """
    Loop: 2100; Segment: CLP.
    """

    id: str
    """
    Unique payment identifier assigned by the converter.
    """
    object_type: str
    """
    Type of this object, set to 'PAYMENT'.
    """
    patient_control_number: str
    """
    Identifier used to track a claim from creation by the health care provider through payment. EDI: CLP01.
    """
    charge_amount: float
    """
    Charge amount. EDI: CLP02.
    """
    payment_amount: float
    """
    Payment amount. EDI: CLP04.
    """
    facility_code: Code | None = None
    """
    Place of service code (professional/dental) or UB facility code (institutional) from the original claim. EDI: CLP08.
    """
    frequency_code: Code | None = None
    """
    Frequency code. EDI: CLP09.
    """
    statement_date_from: date | None = None
    """
    Statement date from. EDI: DTP03 *232.
    """
    statement_date_to: date | None = None
    """
    Statement date to. EDI: DTP03 *233.
    """
    service_date_from: date | None = None
    """
    The earliest service date from service lines.
    """
    service_date_to: date | None = None
    """
    The latest service date from service lines.
    """
    subscriber: PatientSubscriber835 | None = None
    """
    The insured (subscriber) from the original claim if the insured is different from the patient. EDI Loop: 2100.
    """
    patient: PatientSubscriber835 | None = None
    """
    The insured (subscriber) or patient from the original claim. EDI Loop: 2100.
    """
    other_subscribers: list[PatientSubscriber835] | None = None
    """
    Other subscriber; only one other subscriber is allowed on 835. EDI Loop: 2100.
    """
    service_lines: list[PaymentLine] | None = None
    """
    Service lines. EDI Loop: 2110.
    """
    transaction: Transaction835
    """
    Parent EDI transaction for this object. EDI: ST.
    """
    claim_status_code: str | None = None
    """
    Claim status code. EDI: CLP02.
    """
    claim_status: (
        Literal[
            "DENIED",
            "NOT_OUR_CLAIM",
            "PREDETERMINATION_NO_PAYMENT",
            "PRIMARY",
            "PRIMARY_FORWARDED",
            "REVERSAL",
            "SECONDARY",
            "SECONDARY_FORWARDED",
            "TERTIARY",
            "TERTIARY_FORWARDED",
        ]
        | None
    ) = None
    """
    Claim status code translated to a string constant (enum). EDI: CLP02.
    """
    patient_responsibility_amount: float | None = None
    """
    Patient responsibility amount. EDI: CLP05.
    """
    claim_filing_indicator_code: str | None = None
    """
    Claim filing indicator code. EDI: CLP06.
    """
    insurance_plan_type: (
        Literal[
            "AUTOMOBILE_MEDICAL",
            "BCBS",
            "CHAMPUS",
            "COMMERCIAL",
            "EPO",
            "FEDERAL_EMPLOYEE_PROGRAM",
            "HMO",
            "HMO_MEDICARE",
            "INDEMNITY_INSURANCE",
            "MEDICAID",
            "MEDICARE_A",
            "MEDICARE_B",
            "MUTUALLY_DEFINED",
            "OTHER_FEDERAL",
            "OTHER_NON_FEDERAL",
            "POS",
            "PPO",
            "VETERAN_AFFAIRS",
            "WORKERS_COMPENSATION",
        ]
        | None
    ) = None
    """
    Claim filing indicator code translated to a string constant (enum). EDI: CLP06.
    """
    payer_control_number: str | None = None
    """
    Payer control number. EDI: CLP07.
    """
    drg: Code | None = None
    """
    Diagnosis-related group code. Institutional claims only. EDI: CLP11.
    """
    drg_weight: float | None = None
    """
    Adjudicated DRG weight. Institutional claims only. EDI: CLP12.
    """
    discharge_fraction: float | None = None
    """
    Adjudicated discharge fraction. Institutional claims only. This is a percentage expressed as decimal. EDI: CLP13.
    """
    other_claim_related_ids: list[Reference] | None = None
    """
    Other claim-related identifications. EDI: REF.
    """
    supplemental_amounts: list[Amount] | None = None
    """
    Supplemental claim/payment amounts, such as coverage amount, discount amount, etc. EDI: AMT.
    """
    supplemental_quantities: list[Quantity] | None = None
    """
    Supplemental claim/payment quantities. EDI: QTY.
    """
    payer: Party | None = None
    """
    Payer. EDI: N1 *PR.
    """
    payee: Party | None = None
    """
    Payee. EDI: N1 *PE.
    """
    outpatient_adjudication: OutpatientAdjudication | None = None
    """
    Outpatient adjudication. EDI: MOA.
    """
    inpatient_adjudication: InpatientAdjudication | None = None
    """
    Inpatient adjudication. EDI: MIA.
    """
    adjustments: list[Adjustment] | None = None
    """
    Claim adjustments. EDI: CAS.
    """
    coverage_expiration_date: date | None = None
    """
    Coverage expiration date. EDI: DTP03 *036.
    """
    claim_received_date: date | None = None
    """
    Claim received date. EDI: DTP03 *050.
    """
    service_provider: PartyIdName | None = None
    """
    Service provider. EDI: NM1 *SJ.
    """
    crossover_carrier: PartyIdName | None = None
    """
    Crossover carrier. EDI: NM1 *TT.
    """
    corrected_payer: PartyIdName | None = None
    """
    Corrected priority payer, meaning that current payer believes that another payer has priority for making a payment. EDI: NM1 *PR.
    """
    corrected_insured: PartyIdName | None = None
    """
    Corrected insured. EDI: NM1 *74.
    """
    claim_contacts: list[ContactInfo] | None = None
    """
    Claim contacts. EDI: PER.
    """


@final
class ProviderAdjustment(EDIBaseModel):  # pyright: ignore[reportUninitializedInstanceVariable]
    """
    Provider level adjustment information for debit or credit transactions such as, accelerated payments, cost report settlements for a fiscal year and timeliness report penalties unrelated to a specific claim or service. Segment: PLB.
    """

    id: str
    """
    Unique payment identifier assigned by the converter.
    """
    object_type: str
    """
    Type of this object, always set to 'PROVIDER_ADJUSTMENT'.
    """
    provider_identifier: str
    """
    Provider identifier. EDI: PLB01.
    """
    fiscal_period_date: date
    """
    Fiscal period date. EDI: PLB02.
    """
    adjustments: list[ProviderAdjustmentReasonAmount] | None = None
    """
    Adjustments.
    """
    payer: Party | None = None
    """
    Payer. EDI: N1 *PR.
    """
    payee: Party | None = None
    """
    Payee. EDI: N1 *PE.
    """
    transaction: Transaction835 | None = None
    """
    Parent EDI transaction for this adjustment.
    """


class Transaction837(EDIBaseModel):
    control_number: str
    """
    Control number. EDI: ST02.
    """
    transaction_type: str | None = None
    """
    Transaction type translated to string constant, PROF for 837P, INST for 837I, etc. EDI: ST01, ST03.
    """
    hierarchical_structure_code: str | None = None
    """
    Hierarchical structure code. EDI: BHT01.
    """
    purpose_code: str | None = None
    """
    Purpose code. EDI: BHT02.
    """
    originator_application_transaction_id: str | None = None
    """
    Originator application transaction id. EDI: BHT03.
    """
    creation_date: date | None = None
    """
    Creation date. EDI: BHT04.
    """
    creation_time: time | None = None
    """
    Creation time. EDI: BHT05.
    """
    claim_or_encounter_identifier_type: str | None = None
    """
    Claim or encounter identifier type. EDI: BHT06.
    """
    transaction_set_identifier_code: str | None = None
    """
    Transaction set identifier code. EDI: ST01.
    """
    implementation_convention_reference: str | None = None
    """
    Implementation convention reference. EDI: ST03.
    """
    file_info: FileInfo | None = None
    """
    File info.
    """
    sender: PartyIdName | None = None
    """
    Submitter or sender of this transaction.
    """
    receiver: PartyIdName | None = None
    """
    Receiver of this transaction.
    """


@final
class DentClaim(EDIBaseModel):  # pyright: ignore[reportUninitializedInstanceVariable]
    """
    Loop: 2300; Segment: CLM.
    """

    id: str
    """
    Unique payment identifier assigned by the converter.
    """
    object_type: str
    """
    Type of this object, set to 'CLAIM'.
    """
    patient_control_number: str
    """
    Identifier used to track a claim from creation by the health care provider through payment. EDI: CLM01.
    """
    charge_amount: float
    """
    Charge amount. EDI: CLM02.
    """
    patient_paid_amount: float | None = None
    """
    Patient paid amount. EDI: AMT02 *F5.
    """
    facility_code: Code
    """
    Place of service code (professional/dental) or UB facility code (institutional) from the original claim. EDI: CLM05-1.
    """
    frequency_code: Code | None = None
    """
    Frequency code. EDI: CLM05-3.
    """
    service_date_from: date | None = None
    """
    The earliest service date from service lines.
    """
    service_date_to: date | None = None
    """
    The latest service date from service lines.
    """
    subscriber: Subscriber | None = None
    """
    The insured (subscriber). EDI Loop: 2000B.
    """
    patient: Patient | None = None
    """
    Patient if different from the the insured (subscriber). EDI Loop: 2110CA.
    """
    other_subscribers: list[OtherSubscriber] | None = None
    """
    Other subscribers and their payer's information. EDI Loop: 2320.
    """
    service_lines: list[DentLine] | None = None
    """
    Service lines. EDI Loop: 2400.
    """
    transaction: Transaction837
    """
    Parent EDI transaction for this object. EDI: ST.
    """
    provider_signature_indicator: str
    """
    Provider signature indicator. EDI: CLM06.
    """
    assignment_participation_code: str
    """
    Assignment participation code. EDI: CLM07.
    """
    assignment_certification_indicator: str
    """
    Assignment certification indicator. EDI: CLM08.
    """
    release_of_information_code: str
    """
    Release of information code. EDI: CLM09.
    """
    related_cause: RelatedCauseInfo | None = None
    """
    Related cause. EDI: CLM11.
    """
    special_program_code: str | None = None
    """
    Special program code. EDI: CLM12.
    """
    delay_reason_code: str | None = None
    """
    Delay reason code. EDI: CLM20.
    """
    service_authorization_exception_code: str | None = None
    """
    Service authorization exception code. EDI: REF02 *4N.
    """
    referral_number: str | None = None
    """
    Referral number. EDI: REF02 *9F.
    """
    prior_authorization_number: str | None = None
    """
    Prior authorization number. EDI: REF02 *G1.
    """
    original_reference_number: str | None = None
    """
    Original reference number. EDI: REF02 *F8.
    """
    repriced_reference_number: str | None = None
    """
    Repriced reference number. EDI: REF02 *9A.
    """
    adjusted_repriced_reference_number: str | None = None
    """
    Adjusted repriced reference number. EDI: REF02 *9C.
    """
    clearinghouse_trace_number: str | None = None
    """
    Clearinghouse trace number. EDI: REF02 *D9.
    """
    medical_record_number: str | None = None
    """
    Medical record number. EDI: REF02 *EA.
    """
    demonstration_project_identifier: str | None = None
    """
    Demonstration project identifier. EDI: REF02 *P4.
    """
    accident_date: date | None = None
    """
    Accident date. EDI: DTP03 *439.
    """
    orthodontic_banding_date: date | None = None
    """
    Orthodontic banding date. EDI: DTP03 *452.
    """
    repricer_received_date: date | None = None
    """
    Repricer received date. EDI: DTP03 *050.
    """
    orthodontic_info: OrthodonticInfo | None = None
    """
    Orthodontic info.
    """
    tooth_statuses: list[ToothStatus] | None = None
    """
    Tooth statuses.
    """
    predetermination_of_benefits_identifier: str | None = None
    """
    Predetermination of benefits identifier. EDI: REF02 *G3.
    """
    fixed_format_records: list[str] | None = None
    """
    Fixed format records. EDI: K301.
    """
    claim_note: str | None = None
    """
    Free-form comments or instructions. All note segments are concatenated together into this field. EDI: NTE02.
    """
    billing_provider: Provider | None = None
    """
    Billing provider. EDI: NM1 *85.
    """
    pay_to_address: Party | None = None
    """
    Pay to address. EDI: NM1 *87.
    """
    pay_to_plan: Party | None = None
    """
    Pay-to plan for subrogation claims. EDI: NM1 *PE.
    """
    providers: list[Provider] | None = None
    """
    Providers for this claim, except for the billing provider.
    """
    attachments: list[Attachment] | None = None
    """
    Attachments. EDI: PWK.
    """
    contract_info: ContractInfo | None = None
    """
    Contract info. EDI: CN1.
    """


@final
class InstClaim(EDIBaseModel):  # pyright: ignore[reportUninitializedInstanceVariable]
    """
    Loop: 2300; Segment: CLM.
    """

    id: str
    """
    Unique payment identifier assigned by the converter.
    """
    object_type: str
    """
    Type of this object, set to 'CLAIM'.
    """
    patient_control_number: str
    """
    Identifier used to track a claim from creation by the health care provider through payment. EDI: CLM01.
    """
    charge_amount: float
    """
    Charge amount. EDI: CLM02.
    """
    facility_code: Code
    """
    Place of service code (professional/dental) or UB facility code (institutional) from the original claim. EDI: CLM05-1.
    """
    frequency_code: Code | None = None
    """
    Frequency code. EDI: CLM05-3.
    """
    statement_date_from: date | None = None
    """
    Statement date from. EDI: DTP03 *434.
    """
    statement_date_to: date | None = None
    """
    Statement date to. EDI: DTP03 *434.
    """
    service_date_from: date | None = None
    """
    The earliest service date from service lines.
    """
    service_date_to: date | None = None
    """
    The latest service date from service lines.
    """
    subscriber: Subscriber | None = None
    """
    The insured (subscriber). EDI Loop: 2000B.
    """
    patient: Patient | None = None
    """
    Patient if different from the the insured (subscriber). EDI Loop: 2110CA.
    """
    other_subscribers: list[OtherSubscriber] | None = None
    """
    Other subscribers and their payer's information. EDI Loop: 2320.
    """
    service_lines: list[InstLine] | None = None
    """
    Service lines. EDI Loop: 2400.
    """
    transaction: Transaction837
    """
    Parent EDI transaction for this object. EDI: ST.
    """
    assignment_participation_code: str
    """
    Assignment participation code. EDI: CLM07.
    """
    assignment_certification_indicator: str
    """
    Assignment certification indicator. EDI: CLM08.
    """
    release_of_information_code: str
    """
    Release of information code. EDI: CLM09.
    """
    delay_reason_code: str | None = None
    """
    Delay reason code. EDI: CLM20.
    """
    service_authorization_exception_code: str | None = None
    """
    Service authorization exception code. EDI: REF02 *4N.
    """
    referral_number: str | None = None
    """
    Referral number. EDI: REF02 *9F.
    """
    prior_authorization_number: str | None = None
    """
    Prior authorization number. EDI: REF02 *G1.
    """
    original_reference_number: str | None = None
    """
    Original reference number. EDI: REF02 *F8.
    """
    repriced_reference_number: str | None = None
    """
    Repriced reference number. EDI: REF02 *9A.
    """
    adjusted_repriced_reference_number: str | None = None
    """
    Adjusted repriced reference number. EDI: REF02 *9C.
    """
    clearinghouse_trace_number: str | None = None
    """
    Clearinghouse trace number. EDI: REF02 *D9.
    """
    accident_state: str | None = None
    """
    Accident state. EDI: REF02 *LU.
    """
    medical_record_number: str | None = None
    """
    Medical record number. EDI: REF02 *EA.
    """
    peer_review_authorization_number: str | None = None
    """
    Peer review authorization number. EDI: REF02 *G4.
    """
    demonstration_project_identifier: str | None = None
    """
    Demonstration project identifier. EDI: REF02 *P4.
    """
    admission_date_and_hour: AwareDatetime | None = None
    """
    Admission date and hour. EDI: DTP03 *435.
    """
    discharge_time: AwareDatetime | None = None
    """
    Discharge time. EDI: DTP03 *096.
    """
    admission_type_code: str | None = None
    """
    Admission type code. EDI: CL101.
    """
    admission_source_code: str | None = None
    """
    Admission source code. EDI: CL102.
    """
    patient_status_code: str
    """
    Patient status code. EDI: CL103.
    """
    patient_responsibility_amount: float | None = None
    """
    Patient responsibility amount. EDI: AMT02 *F3.
    """
    fixed_format_records: list[str] | None = None
    """
    Fixed format records. EDI: K301.
    """
    claim_note: str | None = None
    """
    Free-form comments or instructions. All note segments are concatenated together into this field. EDI: NTE02.
    """
    billing_note: str | None = None
    """
    Billing note. EDI: NTE02 *ADD.
    """
    billing_provider: Provider | None = None
    """
    Billing provider. EDI: NM1 *85.
    """
    pay_to_address: Party | None = None
    """
    Pay to address. EDI: NM1 *87.
    """
    pay_to_plan: Party | None = None
    """
    Pay-to plan for subrogation claims. EDI: NM1 *PE.
    """
    providers: list[Provider] | None = None
    """
    Providers for this claim, except for the billing provider.
    """
    diags: list[InstDiagnosis]
    """
    Diagnosis codes. EDI: HI.
    """
    drg: Code | None = None
    """
    Drg. EDI: HI *DR.
    """
    procs: list[CodeAndDate] | None = None
    """
    Claim-level procedures. EDI: HI.
    """
    occurrence_spans: list[CodeAndDate] | None = None
    """
    Occurrence spans. EDI: HI *BI.
    """
    occurrences: list[CodeAndDate] | None = None
    """
    Occurrences. EDI: HI *BH.
    """
    value_infos: list[CodeAndAmount] | None = None
    """
    Value infos. EDI: HI *BE.
    """
    conditions: list[Code] | None = None
    """
    Conditions. EDI: HI *BG.
    """
    attachments: list[Attachment] | None = None
    """
    Attachments. EDI: PWK.
    """
    contract_info: ContractInfo | None = None
    """
    Contract info. EDI: CN1.
    """
    conditions_indicators: list[ConditionsIndicator] | None = None
    """
    Conditions indicators. EDI: CRC.
    """


@final
class ProfClaim(EDIBaseModel):  # pyright: ignore[reportUninitializedInstanceVariable]
    """
    Loop: 2300; Segment: CLM.
    """

    id: str
    """
    Unique payment identifier assigned by the converter.
    """
    object_type: str
    """
    Type of this object, set to 'CLAIM'.
    """
    patient_control_number: str
    """
    Identifier used to track a claim from creation by the health care provider through payment. EDI: CLM01.
    """
    charge_amount: float
    """
    Charge amount. EDI: CLM02.
    """
    patient_paid_amount: float | None = None
    """
    Patient paid amount. EDI: AMT02 *F5.
    """
    facility_code: Code
    """
    Place of service code (professional/dental) or UB facility code (institutional) from the original claim. EDI: CLM05-1.
    """
    frequency_code: Code | None = None
    """
    Frequency code. EDI: CLM05-3.
    """
    service_date_from: date | None = None
    """
    The earliest service date from service lines.
    """
    service_date_to: date | None = None
    """
    The latest service date from service lines.
    """
    subscriber: Subscriber | None = None
    """
    The insured (subscriber). EDI Loop: 2000B.
    """
    patient: Patient | None = None
    """
    Patient if different from the the insured (subscriber). EDI Loop: 2110CA.
    """
    other_subscribers: list[OtherSubscriber] | None = None
    """
    Other subscribers and their payer's information. EDI Loop: 2320.
    """
    service_lines: list[ProfLine] | None = None
    """
    Service lines. EDI Loop: 2400.
    """
    transaction: Transaction837
    """
    Parent EDI transaction for this object. EDI: ST.
    """
    provider_signature_indicator: str
    """
    Provider signature indicator. EDI: CLM06.
    """
    assignment_participation_code: str
    """
    Assignment participation code. EDI: CLM07.
    """
    assignment_certification_indicator: str
    """
    Assignment certification indicator. EDI: CLM08.
    """
    release_of_information_code: str
    """
    Release of information code. EDI: CLM09.
    """
    patient_signature_source_code: str | None = None
    """
    Patient signature source code. EDI: CLM10.
    """
    related_cause: RelatedCauseInfo | None = None
    """
    Related cause. EDI: CLM11.
    """
    special_program_code: str | None = None
    """
    Special program code. EDI: CLM12.
    """
    delay_reason_code: str | None = None
    """
    Delay reason code. EDI: CLM20.
    """
    service_authorization_exception_code: str | None = None
    """
    Service authorization exception code. EDI: REF02 *4N.
    """
    referral_number: str | None = None
    """
    Referral number. EDI: REF02 *9F.
    """
    prior_authorization_number: str | None = None
    """
    Prior authorization number. EDI: REF02 *G1.
    """
    original_reference_number: str | None = None
    """
    Original reference number. EDI: REF02 *F8.
    """
    repriced_reference_number: str | None = None
    """
    Repriced reference number. EDI: REF02 *9A.
    """
    adjusted_repriced_reference_number: str | None = None
    """
    Adjusted repriced reference number. EDI: REF02 *9C.
    """
    clearinghouse_trace_number: str | None = None
    """
    Clearinghouse trace number. EDI: REF02 *D9.
    """
    medical_record_number: str | None = None
    """
    Medical record number. EDI: REF02 *EA.
    """
    demonstration_project_identifier: str | None = None
    """
    Demonstration project identifier. EDI: REF02 *P4.
    """
    onset_of_current_illness_or_injury_date: date | None = None
    """
    Onset of current illness or injury date. EDI: DTP03 *431.
    """
    initial_treatment_date: date | None = None
    """
    Initial treatment date. EDI: DTP03 *454.
    """
    last_seen_date: date | None = None
    """
    Last seen date. EDI: DTP03 *304.
    """
    acute_manifestation_date: date | None = None
    """
    Acute manifestation date. EDI: DTP03 *453.
    """
    accident_date: date | None = None
    """
    Accident date. EDI: DTP03 *439.
    """
    last_menstrual_period_date: date | None = None
    """
    Last menstrual period date. EDI: DTP03 *484.
    """
    last_x_ray_date: date | None = None
    """
    Last xray date. EDI: DTP03 *455.
    """
    prescription_date: date | None = None
    """
    Hearing and vision prescription date. EDI: DTP03 *471.
    """
    disability_date_from: date | None = None
    """
    Disability date from. EDI: DTP03 *314.
    """
    disability_date_to: date | None = None
    """
    Disability date to. EDI: DTP03 *361.
    """
    last_worked_date: date | None = None
    """
    Last worked date. EDI: DTP03 *297.
    """
    authorized_return_to_work_date: date | None = None
    """
    Authorized return to work date. EDI: DTP03 *296.
    """
    admission_date: date | None = None
    """
    Admission date for ambulance claims. EDI: DTP03 *435.
    """
    discharge_date: date | None = None
    """
    Discharge date. EDI: DTP03 *096.
    """
    assumed_care_date: date | None = None
    """
    Assumed care date. EDI: DTP03 *090.
    """
    relinquished_care_date: date | None = None
    """
    Relinquished care date. EDI: DTP03 *091.
    """
    property_casualty_first_contact_date: date | None = None
    """
    Property casualty first contact date. EDI: DTP03 *444.
    """
    repricer_received_date: date | None = None
    """
    Repricer received date. EDI: DTP03 *050.
    """
    fixed_format_records: list[str] | None = None
    """
    Fixed format records. EDI: K301.
    """
    claim_note: str | None = None
    """
    Free-form comments or instructions. All note segments are concatenated together into this field. EDI: NTE02.
    """
    billing_provider: Provider | None = None
    """
    Billing provider. EDI: NM1 *85.
    """
    pay_to_address: Party | None = None
    """
    Pay to address. EDI: NM1 *87.
    """
    pay_to_plan: Party | None = None
    """
    Pay-to plan for subrogation claims. EDI: NM1 *PE.
    """
    providers: list[Provider] | None = None
    """
    Providers for this claim, except for the billing provider.
    """
    diags: list[Code]
    """
    Diagnosis codes. EDI: HI.
    """
    procs: list[Code] | None = None
    """
    Anesthesia-related procedures. EDI: HI.
    """
    conditions: list[Code] | None = None
    """
    Conditions. EDI: HI *BG.
    """
    attachments: list[Attachment] | None = None
    """
    Attachments. EDI: PWK.
    """
    contract_info: ContractInfo | None = None
    """
    Contract info. EDI: CN1.
    """
    ambulance_transport_info: AmbulanceTransportInfo | None = None
    """
    Ambulance transport info. EDI: CR1.
    """
    spinal_manipulation_info: SpinalManipulationInfo | None = None
    """
    Spinal manipulation info. EDI: CR2.
    """
    conditions_indicators: list[ConditionsIndicator] | None = None
    """
    Conditions indicators. EDI: CRC.
    """
