"""
Reference data for generating realistic EDI messages.

This file contains medical codes, costs, and other reference data
that will be populated based on research.
"""

# Common place of service codes
from collections.abc import Mapping, Sequence
from typing import Literal

from pydantic import BaseModel


class PlaceOfService(BaseModel):
    code: str
    desc: str
    type: str


PLACE_OF_SERVICE: Sequence[PlaceOfService] = (
    PlaceOfService(code="11", desc="Office", type="OFFICE"),
    PlaceOfService(code="12", desc="Home", type="HOME"),
    PlaceOfService(code="21", desc="Inpatient Hospital", type="INPATIENT_HOSPITAL"),
    PlaceOfService(code="22", desc="Outpatient Hospital", type="OUTPATIENT_HOSPITAL"),
    PlaceOfService(code="23", desc="Emergency Room - Hospital", type="EMERGENCY_ROOM"),
    PlaceOfService(code="24", desc="Ambulatory Surgical Center", type="ASC"),
    PlaceOfService(code="31", desc="Skilled Nursing Facility", type="SNF"),
    PlaceOfService(code="32", desc="Nursing Facility", type="NURSING_FACILITY"),
)


class Payer(BaseModel):
    name: str
    identifier: str
    tax_id: str
    claim_filing_code: str
    plan_type: Literal[
        "AUTOMOBILE_MEDICAL",
        "BCBS",
        "CHAMPUS",
        "COMMERCIAL",
        "EPO",
        "FEDERAL_EMPLOYEE_PROGRAM",
        "HMO",
        "HMO_MEDICARE",
        "INDEMNITY_INSURANCE",
        "MEDICAID",
        "MEDICARE_A",
        "MEDICARE_B",
        "MUTUALLY_DEFINED",
        "OTHER_FEDERAL",
        "OTHER_NON_FEDERAL",
        "POS",
        "PPO",
        "VETERAN_AFFAIRS",
        "WORKERS_COMPENSATION",
    ]


# Common payers
COMMON_PAYERS: Sequence[Payer] = (
    Payer(
        name="BLUE CROSS BLUE SHIELD",
        identifier="BCBS001",
        tax_id="123456789",
        claim_filing_code="BL",
        plan_type="COMMERCIAL",
    ),
    Payer(
        name="AETNA",
        identifier="AETNA001",
        tax_id="234567890",
        claim_filing_code="CI",
        plan_type="COMMERCIAL",
    ),
    Payer(
        name="UNITED HEALTHCARE",
        identifier="UHC001",
        tax_id="345678901",
        claim_filing_code="CI",
        plan_type="COMMERCIAL",
    ),
    Payer(
        name="CIGNA",
        identifier="CIGNA001",
        tax_id="456789012",
        claim_filing_code="CI",
        plan_type="COMMERCIAL",
    ),
    Payer(
        name="HUMANA",
        identifier="HUMANA001",
        tax_id="567890123",
        claim_filing_code="CI",
        plan_type="COMMERCIAL",
    ),
    Payer(
        name="MEDICARE",
        identifier="MEDICARE001",
        tax_id="678901234",
        claim_filing_code="MB",
        plan_type="MEDICARE_B",
    ),
)
type Gender = Literal["FEMALE", "MALE", "UNKNOWN"]

_FEMALE_FIRST_NAMES: Sequence[str] = [
    "ALEXIS",
    "ALICIA",
    "AMANDA",
    "AMY",
    "ANDREA",
    "ANGELA",
    "ANNA",
    "ANNE",
    "ASHLEY",
    "BARBARA",
    "BETTY",
    "BRENDA",
    "CAROL",
    "CAROLYN",
    "CATHERINE",
    "CHRISTINE",
    "CHRISTINA",
    "CYNTHIA",
    "DEBORAH",
    "DEBRA",
    "DIANA",
    "DIANE",
    "DONNA",
    "DOROTHY",
    "ELIZABETH",
    "EMILY",
    "FRANCES",
    "GLORIA",
    "HEATHER",
    "HELEN",
    "IRENE",
    "JANET",
    "JANICE",
    "JEAN",
    "JENNIFER",
    "JESSICA",
    "JOAN",
    "JOANNE",
    "JOYCE",
    "JUDITH",
    "JUDY",
    "JULIE",
    "KAREN",
    "KATHERINE",
    "KATHLEEN",
    "KATHY",
    "KELLY",
    "KIMBERLY",
    "LAURA",
    "LINDA",
    "LISA",
    "LORI",
    "MARGARET",
    "MARIA",
    "MARIE",
    "MARTHA",
    "MARY",
    "MELISSA",
    "MICHELLE",
    "NANCY",
    "NICOLE",
    "PAMELA",
    "PATRICIA",
    "RACHEL",
    "REBECCA",
    "RHONDA",
    "RITA",
    "ROBIN",
    "ROSE",
    "RUTH",
    "SANDRA",
    "SARAH",
    "SHARON",
    "SHIRLEY",
    "STEPHANIE",
    "SUSAN",
    "TAMMY",
    "TERESA",
    "THERESA",
    "VIRGINIA",
    "WANDA",
]
_MALE_FIRST_NAMES: Sequence[str] = [
    "ALAN",
    "ALBERT",
    "ALEXANDER",
    "ANDREW",
    "ANTHONY",
    "ARTHUR",
    "BENJAMIN",
    "BRANDON",
    "BRIAN",
    "BRUCE",
    "CARL",
    "CHARLES",
    "CHRISTOPHER",
    "CRAIG",
    "DANIEL",
    "DAVID",
    "DENNIS",
    "DONALD",
    "DOUGLAS",
    "EDWARD",
    "ERIC",
    "FRANK",
    "GARY",
    "GEORGE",
    "GERALD",
    "GREGORY",
    "HAROLD",
    "HENRY",
    "HOWARD",
    "JACK",
    "JAMES",
    "JASON",
    "JEFFREY",
    "JEREMY",
    "JERRY",
    "JESSE",
    "JOHN",
    "JONATHAN",
    "JOSEPH",
    "JOSHUA",
    "JUSTIN",
    "KEITH",
    "KENNETH",
    "KEVIN",
    "LARRY",
    "LAWRENCE",
    "LOUIS",
    "MARK",
    "MARTIN",
    "MATTHEW",
    "MICHAEL",
    "NICHOLAS",
    "PATRICK",
    "PAUL",
    "PETER",
    "PHILIP",
    "RALPH",
    "RANDY",
    "RAYMOND",
    "RICHARD",
    "ROBERT",
    "ROGER",
    "RONALD",
    "ROY",
    "RYAN",
    "SAMUEL",
    "SCOTT",
    "SEAN",
    "STEPHEN",
    "STEVEN",
    "TERRY",
    "THOMAS",
    "TIMOTHY",
    "TODD",
    "VINCENT",
    "WALTER",
    "WAYNE",
    "WILLIAM",
]


FIRST_NAMES: Mapping[Gender, Sequence[str]] = {
    "FEMALE": _FEMALE_FIRST_NAMES,
    "MALE": _MALE_FIRST_NAMES,
    "UNKNOWN": _FEMALE_FIRST_NAMES + _MALE_FIRST_NAMES,
}

LAST_NAMES = (
    "ADAMS",
    "ALEXANDER",
    "ALLEN",
    "ANDERSON",
    "BAILEY",
    "BAKER",
    "BARNES",
    "BELL",
    "BENNETT",
    "BROOKS",
    "BROWN",
    "BRYANT",
    "BUTLER",
    "CAMPBELL",
    "CARTER",
    "CHEN",
    "CLARK",
    "COLEMAN",
    "COLLINS",
    "COOK",
    "COOPER",
    "COX",
    "DAVIS",
    "DIAZ",
    "EDWARDS",
    "EVANS",
    "FISHER",
    "FOSTER",
    "FLORES",
    "GARCIA",
    "GONZALEZ",
    "GRAY",
    "GREEN",
    "GRIFFIN",
    "HALL",
    "HARRIS",
    "HAYES",
    "HENDERSON",
    "HERNANDEZ",
    "HILL",
    "HOWARD",
    "HUGHES",
    "JACKSON",
    "JAMES",
    "JENKINS",
    "JOHNSON",
    "JONES",
    "KELLY",
    "KING",
    "KUMAR",
    "LEE",
    "LEWIS",
    "LONG",
    "LOPEZ",
    "MARTIN",
    "MARTINEZ",
    "MILLER",
    "MITCHELL",
    "MOORE",
    "MORGAN",
    "MORRIS",
    "MURPHY",
    "MYERS",
    "NGUYEN",
    "NELSON",
    "OWENS",
    "PARKER",
    "PATEL",
    "PEREZ",
    "PETERSON",
    "PHILLIPS",
    "POWELL",
    "PRICE",
    "RAMIREZ",
    "REED",
    "RICHARDSON",
    "RIVERA",
    "ROBERTS",
    "ROBINSON",
    "RODRIGUEZ",
    "RUSSELL",
    "SANCHEZ",
    "SANDERS",
    "SCOTT",
    "SIMMONS",
    "SMITH",
    "STEWART",
    "SULLIVAN",
    "TAYLOR",
    "THOMAS",
    "THOMPSON",
    "TORRES",
    "TURNER",
    "WALKER",
    "WARD",
    "WATSON",
    "WHITE",
    "WILLIAMS",
    "WILSON",
    "WOOD",
    "WRIGHT",
    "YANG",
    "YOUNG",
)


class CityState(BaseModel):
    city: str
    state: str
    zip: str


CITIES_STATES: Sequence[CityState] = [
    CityState(city="ALBUQUERQUE", state="NM", zip="87101"),
    CityState(city="ARLINGTON", state="TX", zip="76001"),
    CityState(city="ATLANTA", state="GA", zip="30301"),
    CityState(city="AUSTIN", state="TX", zip="78701"),
    CityState(city="BALTIMORE", state="MD", zip="21201"),
    CityState(city="BIRMINGHAM", state="AL", zip="35201"),
    CityState(city="BOSTON", state="MA", zip="02101"),
    CityState(city="CHARLOTTE", state="NC", zip="28201"),
    CityState(city="CHICAGO", state="IL", zip="60601"),
    CityState(city="CLEVELAND", state="OH", zip="44101"),
    CityState(city="COLUMBUS", state="OH", zip="43201"),
    CityState(city="DALLAS", state="TX", zip="75201"),
    CityState(city="DENVER", state="CO", zip="80201"),
    CityState(city="DETROIT", state="MI", zip="48201"),
    CityState(city="EL PASO", state="TX", zip="79901"),
    CityState(city="FORT WORTH", state="TX", zip="76101"),
    CityState(city="FRESNO", state="CA", zip="93701"),
    CityState(city="HONOLULU", state="HI", zip="96801"),
    CityState(city="HOUSTON", state="TX", zip="77001"),
    CityState(city="INDIANAPOLIS", state="IN", zip="46201"),
    CityState(city="JACKSONVILLE", state="FL", zip="32099"),
    CityState(city="KANSAS CITY", state="MO", zip="64101"),
    CityState(city="LAS VEGAS", state="NV", zip="89101"),
    CityState(city="LONG BEACH", state="CA", zip="90801"),
    CityState(city="LOS ANGELES", state="CA", zip="90001"),
    CityState(city="LOUISVILLE", state="KY", zip="40201"),
    CityState(city="MEMPHIS", state="TN", zip="38101"),
    CityState(city="MIAMI", state="FL", zip="33101"),
    CityState(city="MILWAUKEE", state="WI", zip="53201"),
    CityState(city="MINNEAPOLIS", state="MN", zip="55401"),
    CityState(city="NASHVILLE", state="TN", zip="37201"),
    CityState(city="NEW ORLEANS", state="LA", zip="70112"),
    CityState(city="NEW YORK", state="NY", zip="10001"),
    CityState(city="OAKLAND", state="CA", zip="94601"),
    CityState(city="OKLAHOMA CITY", state="OK", zip="73101"),
    CityState(city="OMAHA", state="NE", zip="68101"),
    CityState(city="PHILADELPHIA", state="PA", zip="19101"),
    CityState(city="PHOENIX", state="AZ", zip="85001"),
    CityState(city="PITTSBURGH", state="PA", zip="15201"),
    CityState(city="PORTLAND", state="OR", zip="97201"),
    CityState(city="RALEIGH", state="NC", zip="27601"),
    CityState(city="RICHMOND", state="VA", zip="23218"),
    CityState(city="SACRAMENTO", state="CA", zip="95814"),
    CityState(city="SAN ANTONIO", state="TX", zip="78201"),
    CityState(city="SAN DIEGO", state="CA", zip="92101"),
    CityState(city="SAN FRANCISCO", state="CA", zip="94101"),
    CityState(city="SAN JOSE", state="CA", zip="95101"),
    CityState(city="SEATTLE", state="WA", zip="98101"),
    CityState(city="ST LOUIS", state="MO", zip="63101"),
    CityState(city="TAMPA", state="FL", zip="33601"),
    CityState(city="TUCSON", state="AZ", zip="85701"),
    CityState(city="TULSA", state="OK", zip="74101"),
    CityState(city="VIRGINIA BEACH", state="VA", zip="23450"),
    CityState(city="WASHINGTON", state="DC", zip="20001"),
    CityState(city="WICHITA", state="KS", zip="67201"),
    CityState(city="AKRON", state="OH", zip="44301"),
    CityState(city="ALBANY", state="NY", zip="12201"),
    CityState(city="ALEXANDRIA", state="VA", zip="22301"),
    CityState(city="AMARILLO", state="TX", zip="79101"),
    CityState(city="ANAHEIM", state="CA", zip="92801"),
    CityState(city="ANCHORAGE", state="AK", zip="99501"),
    CityState(city="ANN ARBOR", state="MI", zip="48103"),
    CityState(city="ARLINGTON", state="VA", zip="22201"),
    CityState(city="AURORA", state="CO", zip="80010"),
    CityState(city="AURORA", state="IL", zip="60502"),
    CityState(city="BAKERSFIELD", state="CA", zip="93301"),
    CityState(city="BATON ROUGE", state="LA", zip="70801"),
    CityState(city="BELLEVUE", state="WA", zip="98004"),
    CityState(city="BILLINGS", state="MT", zip="59101"),
    CityState(city="BOISE", state="ID", zip="83701"),
    CityState(city="BUFFALO", state="NY", zip="14201"),
    CityState(city="CEDAR RAPIDS", state="IA", zip="52401"),
    CityState(city="CHANDLER", state="AZ", zip="85224"),
    CityState(city="CHESAPEAKE", state="VA", zip="23320"),
    CityState(city="CHULA VISTA", state="CA", zip="91910"),
    CityState(city="CINCINNATI", state="OH", zip="45201"),
    CityState(city="COLORADO SPRINGS", state="CO", zip="80901"),
    CityState(city="CORPUS CHRISTI", state="TX", zip="78401"),
    CityState(city="DURHAM", state="NC", zip="27701"),
    CityState(city="ELK GROVE", state="CA", zip="95624"),
    CityState(city="FORT WAYNE", state="IN", zip="46801"),
    CityState(city="FORT LAUDERDALE", state="FL", zip="33301"),
    CityState(city="GARLAND", state="TX", zip="75040"),
    CityState(city="GILBERT", state="AZ", zip="85233"),
    CityState(city="GLENDALE", state="AZ", zip="85301"),
    CityState(city="GRAND RAPIDS", state="MI", zip="49501"),
    CityState(city="GREENSBORO", state="NC", zip="27401"),
    CityState(city="HENDERSON", state="NV", zip="89002"),
    CityState(city="HIALEAH", state="FL", zip="33010"),
    CityState(city="IRVINE", state="CA", zip="92602"),
    CityState(city="IRVING", state="TX", zip="75038"),
    CityState(city="JERSEY CITY", state="NJ", zip="07302"),
    CityState(city="KNOXVILLE", state="TN", zip="37901"),
    CityState(city="LAREDO", state="TX", zip="78040"),
    CityState(city="LEXINGTON", state="KY", zip="40502"),
    CityState(city="LINCOLN", state="NE", zip="68501"),
    CityState(city="LUBBOCK", state="TX", zip="79401"),
    CityState(city="MADISON", state="WI", zip="53701"),
    CityState(city="MESA", state="AZ", zip="85201"),
    CityState(city="MONTGOMERY", state="AL", zip="36101"),
    CityState(city="NAPLES", state="FL", zip="34101"),
    CityState(city="NEWARK", state="NJ", zip="07101"),
    CityState(city="NORFOLK", state="VA", zip="23501"),
    CityState(city="NORTH LAS VEGAS", state="NV", zip="89030"),
    CityState(city="OCEANSIDE", state="CA", zip="92054"),
    CityState(city="ORLANDO", state="FL", zip="32801"),
    CityState(city="OXNARD", state="CA", zip="93030"),
    CityState(city="PLANO", state="TX", zip="75023"),
    CityState(city="PROVIDENCE", state="RI", zip="02901"),
    CityState(city="RENO", state="NV", zip="89501"),
    CityState(city="ROCHESTER", state="NY", zip="14601"),
    CityState(city="SALT LAKE CITY", state="UT", zip="84101"),
    CityState(city="SANTA ANA", state="CA", zip="92701"),
    CityState(city="SANTA CLARA", state="CA", zip="95050"),
    CityState(city="SANTA ROSA", state="CA", zip="95401"),
    CityState(city="SAVANNAH", state="GA", zip="31401"),
    CityState(city="SCOTTSDALE", state="AZ", zip="85251"),
    CityState(city="SHREVEPORT", state="LA", zip="71101"),
    CityState(city="SPOKANE", state="WA", zip="99201"),
    CityState(city="SPRINGFIELD", state="MO", zip="65801"),
    CityState(city="STOCKTON", state="CA", zip="95201"),
    CityState(city="SYRACUSE", state="NY", zip="13201"),
    CityState(city="TALLAHASSEE", state="FL", zip="32301"),
    CityState(city="TOLEDO", state="OH", zip="43601"),
    CityState(city="TORRANCE", state="CA", zip="90501"),
    CityState(city="VANCOUVER", state="WA", zip="98660"),
    CityState(city="VERO BEACH", state="FL", zip="32960"),
    CityState(city="WACO", state="TX", zip="76701"),
    CityState(city="WARREN", state="MI", zip="48088"),
    CityState(city="WEST PALM BEACH", state="FL", zip="33401"),
    CityState(city="WINSTON SALEM", state="NC", zip="27101"),
    CityState(city="WORCESTER", state="MA", zip="01601"),
    CityState(city="YONKERS", state="NY", zip="10701"),
]
